# -*- coding: utf-8 -*-
"""EXNO1_DS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JdjZpBemsYNDgM_0iKLh-L90mfjjbXAS
"""

import pandas as pd

#READ CSV FILE HERE
df= pd.read_csv('Data_set.csv')

#DISPLAY THE INFORMATION ABOUT CSV AND RUN THE BASIC DATA ANALYSIS FUNCTIONS
print(df.describe())

#CHECK OUT NULL VALUES IN DATA SET USING FUNCTION
print(df.isnull().sum())

#DISPLAY THE SUM ON NULL VALUES IN EACH ROWS
print(df.isnull().sum(axis=1))

#DROP NULL VALUES
df.dropna()

#FILL NULL VALUES WITH CONSTANT VALUE "O"
df.fillna("O")

#FILL NULL VALUES WITH ffill or bfill METHOD
df.fillna(method="ffill")

#CALCULATE MEAN VALUE OF A COLUMN AND FILL IT WITH NULL VALUES
mean=df['num_episodes'].mean()
df.fillna(mean)

#DROP NULL VALUES
df.dropna()

import pandas as pd
import seaborn as sns
import numpy as np

age=[1,3,28,27,25,92,30,39,40,50,26,24,29,94]
af=pd.DataFrame(age)
af

#USE BOXPLOT FUNCTION HERE TO DETECT OUTLIER
sns.boxplot(af)

#PERFORM IQR METHOD AND DETECT OUTLIER VALUES
Q1=af.quantile(0.25)
Q3=af.quantile(0.75)
IQR=Q3-Q1
print(IQR)

#REMOVE OUTLIERS
af=af[~((af<(Q1-1.5*IQR))|(af>(Q3+1.5*IQR))).any(axis=1)]
af

#USE BOXPLOT FUNCTION HERE TO CHECK OUTLIER IS REMOVED
sns.boxplot(af)

from scipy import stats #STATS METHOD IS USED TO IMPLEMENT Z SCORE METHOD

data=[1,12,15,18,21,24,27,30,33,36,39,42,45,48,51,54,57,60,63,66,69,72,75,78,81,84,87,90,93,96,99,158]
df=pd.DataFrame(data)

#USE BOXPLOT FUNCTION HERE TO DETECT OUTLIER
sns.boxplot(df)

#PERFORM Z SCORE METHOD AND DETECT OUTLIER VALUES
z=np.abs(stats.zscore(df))
print(z)

#REMOVE OUTLIERS
df=df[(z<3).all(axis=1)]
df

#USE BOXPLOT FUNCTION HERE TO CHECK OUTLIER IS REMOVED
sns.boxplot(df)